import pandas as pd
df = pd.read_excel('sample_strategy_data.xlsx')
print("=== DTYPES ===")
print(df.dtypes)
print("\n=== TX TYPES ===")
print(df.iloc[:,2].value_counts())
print("\n=== GROUPS ===")
print(df.iloc[:,3].value_counts())
print(f"\n=== DATE RANGE ===")
print(f"{df.iloc[:,7].min()} → {df.iloc[:,7].max()}")
print(f"\n=== UNIQUE ITEMS: {df.iloc[:,0].nunique()} ===")
print(sorted(df.iloc[:,0].unique()))
print("\n=== PURCHASE ROWS (first 5) ===")
buys = df[df.iloc[:,2]=='خرید']
print(f"Total: {len(buys)}")
print(buys.head(5).to_string())
print("\n=== WASTE ROWS (first 3) ===")
w = df[df.iloc[:,2]=='ضایعات']
print(f"Total: {len(w)}")
print(w.head(3).to_string())
print("\n=== PRICE STATS (purchases only) ===")
print(f"unit_price > 0: {(buys.iloc[:,4] > 0).sum()}")
print(f"unit_price == 0: {(buys.iloc[:,4] == 0).sum()}")
print(f"total_amount > 0: {(buys.iloc[:,6] > 0).sum()}")
